// www/src/routes/scenes/index.tsx
import clsx from "clsx";
import toast from "solid-toast";
import { For, Match, Show, Switch, createResource } from "solid-js";
import { Portal } from "solid-js/web";
import { A, useNavigate } from "@solidjs/router";
import { Menu } from "@ark-ui/solid";
import { Layers3, MenuIcon, RefreshCw, SquarePlus } from "lucide-solid";
import { pb } from "$app/connections/pocketbase";
import ToasterCard from "$app/components/layouts/ToasterCard";
import type { Scene } from "$lib/core";

export default function ScenesPage() {
  const navigate = useNavigate();
  const [scenes, { refetch, mutate }] = createResource(
    "scenes.list",
    async () => {
      return (
        await pb.collection<{ id: string; label: string }>("scenes").getList(undefined, undefined, {
          fields: "id,label",
        })
      ).items;
    },
    {
      initialValue: [],
    },
  );

  const newScene = async () => {
    const scene = { label: "Untitled Scene", plugins: [], sources: [] } satisfies Scene;
    const result = await pb
      .collection("scenes")
      .create({ ...scene, owner: pb.authStore.modelStore()?.id, visibility: "PRIVATE" });

    mutate((prev) => [...prev, { id: result.id, label: "Untitled Scene" }]);
    navigate(`/scenes/edit/${result.id}`);
  };

  const deleteScene = async (id: string) => {
    await pb.collection("scenes").delete(id);

    mutate((prev) => [...prev.filter((s) => s.id !== id)]);
  };

  return (
    <>
      <ToasterCard
        title={
          <h1 class="flex gap-2">
            <Layers3 size="3rem" /> Scenes
          </h1>
        }
        actions={
          <>
            <button
              class={clsx([scenes.loading && "pointer-events-none animate-spin"])}
              onclick={() => refetch()}
            >
              <RefreshCw />
            </button>
            <button
              class="flex gap-1 rounded bg-white p-1 shadow"
              onclick={() => {
                toast.promise(newScene(), {
                  loading: "Creating new scene...",
                  success: "New scene created!",
                  error: (err) => `Failed to create scene: ${err.message}`,
                });
              }}
            >
              <SquarePlus /> New Scene
            </button>
          </>
        }
        footer={<A href="/">Back</A>}
      >
        <div class="py-2">
          <Switch>
            <Match when={scenes.error}>
              <div class="absolute inset-0 grid h-full place-content-center">
                <div>
                  <p>Uh oh</p>
                  <Switch>
                    <Match when={scenes.error.status === 401}>
                      <p>Looks like you're not signed in...</p>
                      <A class="underline" href="/account">
                        Sign in
                      </A>
                    </Match>
                    <Match when={scenes.error.status === 401}>
                      <p>Something wen't wrong: {scenes.error.response.message}</p>
                    </Match>
                  </Switch>
                </div>
              </div>
            </Match>
            <Match when={scenes()}>
              <ul>
                <For each={scenes()}>
                  {(item) => (
                    <li class="px-2 hover:bg-black/5">
                      <Menu.Root positioning={{ placement: "bottom" }}>
                        <div class="flex w-full justify-between">
                          <Menu.ContextTrigger
                            class="w-full"
                            asChild={(props) => (
                              <A href={`/scenes/edit/${item.id}`} {...props}>
                                {item.label}
                              </A>
                            )}
                          />
                          <Menu.Trigger>
                            <MenuIcon size="1rem" />
                          </Menu.Trigger>
                        </div>
                        <Portal>
                          <Menu.Positioner>
                            <Menu.Content class="min-w-14 rounded bg-white py-2 shadow *:cursor-pointer *:px-2">
                              <Menu.Item
                                value="view"
                                asChild={(props) => (
                                  <A
                                    href={`/scenes/view/${item.id}${pb.authStore.modelStore()?.streamKey ? `?sk=${pb.authStore.modelStore()!.streamKey}` : ""}`}
                                    target="_blank"
                                    {...props}
                                  >
                                    View in new tab
                                  </A>
                                )}
                              />
                              <Menu.Item
                                class="bg-red-100 text-red-950"
                                value="delete"
                                onclick={() => {
                                  toast.promise(deleteScene(item.id), {
                                    loading: "Deleting scene...",
                                    success: "Deleted scene!",
                                    error: (err) => `Failed to delete scene: ${err.message}`,
                                  });
                                }}
                              >
                                Delete
                              </Menu.Item>
                            </Menu.Content>
                          </Menu.Positioner>
                        </Portal>
                      </Menu.Root>
                    </li>
                  )}
                </For>
                <Show when={scenes().length === 0}>
                  <p class="w-full text-center text-zinc-400">
                    {scenes.loading ? "Loading..." : "No scenes yet! I wonder what we'll create?"}
                  </p>
                </Show>
              </ul>
            </Match>
          </Switch>
        </div>
      </ToasterCard>
    </>
  );
}

// admin/src/routes/(dashboard)/scenes/+page.svelte
<script lang="ts">
  import clsx from "clsx";
  import toast from "svelte-french-toast";
  import { fly } from "svelte/transition";
  import { DropdownMenu } from "bits-ui";
  import { EllipsisVertical, PlusSquare } from "lucide-svelte";
  import { navigating } from "$app/stores";
  import { goto } from "$app/navigation";
  import { DEFAULT_SCRIPTS } from "$lib/editor/scripts";

  import type { PageData } from "./$types";
  export let data: PageData;
  const { user } = data;

  let localScenes = data.suspense.initial.then((i) => i.scenes);
  let rename: string = "";

  const focus = (el: HTMLElement) => {
    setTimeout(() => {
      el.focus();
    }, 100);
  };
</script>

<button
  class="mb-4 flex w-full items-center justify-center gap-1 rounded border-2 border-dashed border-slate-400 bg-slate-200 py-5 text-slate-400 hover:bg-slate-300 hover:text-slate-600"
  on:click={async () => {
    await toast.promise(
      data.pb
        .collection("scenes")
        .create({
          owner: $user?.id,
          label: "Untitled Scene",
          scripts: [...DEFAULT_SCRIPTS],
          sources: "",
          visibility: "PRIVATE",
        })
        .then((scene) => goto(`/breakfast/scenes/edit/${scene.id}`)),
      {
        loading: "Creating new scene....",
        success: "New scene created!",
        error: (err) => `Failed to create new scene: ${err.message}`,
      },
    );
  }}
>
  <p>New Scene</p>
  <PlusSquare />
</button>

<ul role="list" class="divide-y divide-gray-100">
  {#await localScenes}
    <p>Loading</p>
  {:then scenes}
    {#if scenes.length === 0}
      <p>No scenes yet!</p>
    {/if}
    {#each scenes as scene, idx}
      <li
        class={clsx([
          "flex items-center justify-between gap-x-6 py-5 first:pt-0 last:pb-0",
          $navigating?.to?.route.id === "/(dashboard)/scenes/edit/[id]" &&
            $navigating.to.params?.id === scene.id &&
            "animate-pulse",
        ])}
      >
        <div class="min-w-0">
          <div class="flex items-start gap-x-3">
            {#if rename === scene.id}
              <input
                class="text-sm font-semibold leading-6 text-gray-900"
                value={scene.label}
                on:keydown={({ key, currentTarget }) => {
                  if (key === "Enter") currentTarget.blur();
                }}
                on:blur={({ currentTarget: { value } }) => {
                  if (value !== scene.label) {
                    toast.promise(
                      data.pb.collection("scenes").update(scene.id, {
                        label: value,
                      }),
                      {
                        loading: "Renaming scene...",
                        success: "Scene renamed!",
                        error: (err) => `Failed to rename scene: ${err.message}`,
                      },
                    );
                    scene.label = value;
                  }
                  rename = "";
                }}
                use:focus
              />
            {:else}
              <p class="text-sm font-semibold leading-6 text-gray-900">{scene.label}</p>
            {/if}
          </div>
          <div class="mt-1 flex items-center gap-x-2 text-xs leading-5 text-gray-500">
            <p class="truncate">{scene.visibility} | Created by {$user?.username}</p>
          </div>
        </div>
        <div class="flex flex-none items-center gap-x-4">
          <a
            href="/breakfast/scenes/edit/{scene.id}"
            class="hidden rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:block"
          >
            Edit Scene
          </a>
          <div class="relative flex-none">
            <DropdownMenu.Root>
              <DropdownMenu.Trigger class="-m-2.5 block p-2.5 text-gray-500 hover:text-gray-900">
                <span class="sr-only">Open options</span>
                <EllipsisVertical class="h-5 w-5" />
              </DropdownMenu.Trigger>
              <DropdownMenu.Content
                class="w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none"
                transition={fly}
                transitionConfig={{ y: -20, duration: 100 }}
              >
                <DropdownMenu.Item
                  class="block px-3 py-1 text-sm leading-6 text-gray-900"
                  href="/breakfast/scenes/edit/{scene.id}"
                >
                  Edit
                </DropdownMenu.Item>
                <DropdownMenu.Item
                  class="block cursor-pointer px-3 py-1 text-sm leading-6 text-gray-900"
                  on:click={() => {
                    rename = scene.id;
                  }}
                >
                  Rename
                </DropdownMenu.Item>
                <DropdownMenu.Item
                  class="block px-3 py-1 text-sm leading-6 text-gray-900"
                  href="/scenes/render/{scene.id}"
                  target="_blank"
                >
                  View
                </DropdownMenu.Item>
                <DropdownMenu.Separator class="border-t border-slate-200" />
                <DropdownMenu.Item
                  class="block cursor-pointer px-3 py-1 text-sm leading-6 text-red-900"
                  on:click={async () => {
                    await toast.promise(data.pb.collection("scenes").delete(scene.id), {
                      loading: "Deleting scene...",
                      success: "Scene deleted!",
                      error: (err) => `Failed to delete scene: ${err.message}`,
                    });
                    scenes.splice(idx, 1);
                    localScenes = Promise.resolve(scenes);
                  }}
                >
                  Delete
                </DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Root>
          </div>
        </div>
      </li>
    {/each}
  {/await}
</ul>
